#!/usr/bin/env sh
export MAC_PATH="$(cd "$(dirname "$0")"; pwd -P)" # the location of this script
source "${MAC_PATH}/lib/utils.sh"

# required
module 'homebrew'

# to setup the machine, list the modules that apply
module 'dotfiles'
module 'terminal'
module 'vim'
module 'java'
module 'sophos'

echo "\n${BGre}Your Mac is ready.${RCol}\n"
