#!/usr/bin/env sh

lib "colors"

install_or_update_homebrew() {
  if ! command -v brew >/dev/null; then
    echo "${BBlue}installing brew...${RCol}"
    curl -fsS 'https://git.io/pVOl' | ruby
    echo "${Pur}brew installed${RCol}"
  else
    echo "${BPur}brew exists, updating${RCol}"
    echo "${BPur}`brew update`${RCol}"
  fi
}

tap_brew_bundle() {
  brew tap | grep -q "homebrew/bundle"
  if [ $? -eq 1 ]; then
    brew tap homewbrew/bundle
  fi
}

install_or_update_homebrew
tap_brew_bundle
