#!/usr/bin/env sh

include 'utils'

install_or_update_homebrew() {
  if ! command -v brew >/dev/null; then
    curl -fsS 'https://git.io/pVOl' | ruby
    logdebug "brew installed"
  else
    logdebug "`brew update`"
  fi
}

tap_brew_bundle() {
  brew tap | grep -q "homebrew/bundle"
  if [ $? -eq 1 ]; then
    brew tap homewbrew/bundle
  fi
}

install_or_update_homebrew
tap_brew_bundle
