#!/usr/bin/env sh

# Install Vundle
mkdir -p ${HOME}/.vim/bundle
[ -d ${HOME}/.vim/bundle/Vundle.vim ] || git clone https://github.com/VundleVim/Vundle.vim.git ${HOME}/.vim/bundle/Vundle.vim

# Install Vundle plugins
vim +PluginInstall +qall
